baseURL = "https://c-d-t.github.io/portfolio"
languageCode = "en-us"
title = "Casey Tai"
publishDir = "docs"

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/project"
    weight = -2
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = -1
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 0
